[[redirects]]
  from = "/socket.io/*"
  to = "https://api.gringo.ezyy.cloud/socket.io/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/*"
  to = "https://api.gringo.ezyy.cloud/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 