[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/api/*"
  to = "https://api.gringo.ezyy.cloud/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 