[build]
  publish = "dist"
  command = "npm install && tsc && vite build && node create-redirects.js"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "https://api.gringo.ezyy.cloud/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://api.gringo.ezyy.cloud/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 